/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=workers/app/.dev.vars.example --include-runtime=false workers/app/worker-configuration.d.ts` (hash: e7541a6a1d286aa5295980f12c23cf97)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	OPENROUTER_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_API_KEY">> {}
}
