/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=workers/app/.dev.vars.example --include-runtime=false workers/app/worker-configuration.d.ts` (hash: a2b4f1adb642bff831c0d60835d0d255)
interface __BaseEnv_Env {
	SYNC_CONTROL: KVNamespace;
	EVENTS_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	CONFLUENT_TOPIC: "marginalia.events.v1";
	OPENROUTER_API_KEY: string;
	MARGINALIA_SYNC_TOKEN_SHA256: string;
	MARGINALIA_TRUSTED_USER_ID: string;
	CONFLUENT_REST_ENDPOINT: string;
	CONFLUENT_CLUSTER_ID: string;
	CONFLUENT_API_KEY: string;
	CONFLUENT_API_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONFLUENT_TOPIC" | "OPENROUTER_API_KEY" | "MARGINALIA_SYNC_TOKEN_SHA256" | "MARGINALIA_TRUSTED_USER_ID" | "CONFLUENT_REST_ENDPOINT" | "CONFLUENT_CLUSTER_ID" | "CONFLUENT_API_KEY" | "CONFLUENT_API_SECRET">> {}
}
